{
    "name": "SPSL Access Control",
    "version": "19.0.1.0.3",
    "summary": "25 user roles, CRUD access rules, field-level security for SPSL",
    "author": "SPSL",
    "category": "Hidden",
    "license": "LGPL-3",
    "depends": [
        "base",
        "account",
        "sale",
        "purchase",
        "stock",
        "hr",
        "hr_payroll_community",
        "hr_holidays",
        "crm",
        "sales_team",
        "operating_unit",
        "operating_unit_access_all",
        "analytic",
    ],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "security/field_access_rules.xml",
        "security/record_rules.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
